# Generated by Django 6.0 on 2026-01-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_options_alter_subscription_options_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="processed",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processing_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authorized", "Authorized"),
                    ("verified", "Verified"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="tenants.tenant",
            ),
        ),
    ]
