# Generated by Django 6.0 on 2026-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_superadmin_user_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
