import os
import random
import uuid
import string
from locust import HttpUser, task, between

# --- HARDCODE TOKENS HERE ---
# Paste your tokens here so you can just run 'locust'
AUTH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczNzM2MzAyLCJpYXQiOjE3NzM3MzI3MDIsImp0aSI6ImE2YWYwZmQ1NmY4MDQ1ZWZhN2Y1OGNkNjJjZDY5NTc4IiwidXNlcl9pZCI6IjYxOWYzYTY4LThkMGEtNDk0Yy1iOTA1LTEyYWQ2NjRmMDZlOSJ9.SHXWKjGkENnJROWSCcpS0ZvN7JfHYrq56d7wuAvCtaI"
SUPER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczNzM2MzAyLCJpYXQiOjE3NzM3MzI3MDIsImp0aSI6ImQzYzFhOTY5MDNiZTRlYmNhMzNjZjI3NmUyODcwODFjIiwidXNlcl9pZCI6ImRlZTQ2YjE1LTk2YTgtNDk5YS1iYWY4LTkzOGI3NjNkYmMwYSJ9.H3OV3ddQch11jWiG7zX0t7zIIteTUa1bbefS-d2B7xA"
# ----------------------------

class FoodieUser(HttpUser):
    wait_time = between(1, 4)
    
    def on_start(self):
        """Called when a virtual user starts."""
        self.auth_token = AUTH_TOKEN if AUTH_TOKEN != "PASTE_TENANT_ADMIN_TOKEN_HERE" else os.getenv("LOCUST_AUTH_TOKEN")
        self.super_token = SUPER_TOKEN if SUPER_TOKEN != "PASTE_SUPERADMIN_TOKEN_HERE" else os.getenv("LOCUST_SUPERADMIN_TOKEN")
        
        self.headers = {
            "Authorization": f"Bearer {self.auth_token}",
            "Content-Type": "application/json"
        }
        self.super_headers = {
            "Authorization": f"Bearer {self.super_token}",
            "Content-Type": "application/json"
        } if self.super_token else self.headers

        self.cuisine_ids = []
        self.recipe_ids = []
        self.fetch_initial_data()

    def fetch_initial_data(self):
        """Pre-fetch some IDs so we can do realistic writes."""
        # 1. Fetch Cuisines
        response = self.client.get("/api/v1/cuisines/", headers=self.headers, name="Init: Fetch Cuisines")
        if response.status_code == 200:
            results = response.json().get("results", [])
            self.cuisine_ids = [c["id"] for c in results]

        # 2. Fetch some Recipes
        response = self.client.get("/api/v1/recipes/", headers=self.headers, name="Init: Fetch Recipes")
        if response.status_code == 200:
            results = response.json().get("results", [])
            self.recipe_ids = [r["id"] for r in results]

    @task(5)
    def view_recipes(self):
        self.client.get("/api/v1/recipes/", headers=self.headers, name="Read: List Recipes")

    @task(1)
    def create_recipe(self):
        """Phase 3: Test Write performance (POST)."""
        if not self.cuisine_ids:
            return
            
        # Recipe names cannot have numbers or special characters due to validator
        random_suffix = ''.join(random.choices(string.ascii_lowercase, k=5))
        payload = {
            "name": f"Stress Test Recipe {random_suffix}",
            "description": "Generated by Locust during write-load phase.",
            "preparation_steps": "1. Mix ingredients. 2. Cook. 3. Serve.",
            "cooking_time": random.randint(10, 60),
            "cuisine_id": random.choice(self.cuisine_ids),
            "sharing_status": "PUBLIC"
        }
        
        with self.client.post("/api/v1/recipes/", json=payload, headers=self.headers, name="Write: Create Recipe", catch_response=True) as response:
            if response.status_code == 201:
                new_id = response.json().get("id")
                if new_id:
                    self.recipe_ids.append(new_id)
            else:
                response.failure(f"Failed to create recipe: {response.status_code} - {response.text}")

    @task(1)
    def update_recipe(self):
        """Phase 3: Test Update performance (PATCH)."""
        if not self.recipe_ids:
            return
            
        recipe_id = random.choice(self.recipe_ids)
        random_suffix = ''.join(random.choices(string.ascii_lowercase, k=5))
        payload = {
            "name": f"Updated Name {random_suffix}",
            "cooking_time": random.randint(10, 120)
        }
        with self.client.patch(f"/api/v1/recipes/{recipe_id}/", json=payload, headers=self.headers, name="Write: Patch Recipe", catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Failed to patch recipe: {response.status_code} - {response.text}")

    @task(2)
    def view_users(self):
        self.client.get("/api/v1/users/", headers=self.headers, name="Read: List Users")

    @task(1)
    def view_orders(self):
        self.client.get("/api/v1/orders/", headers=self.headers, name="Read: List Orders")

    @task(1)
    def view_payment_history(self):
        self.client.get("/api/v1/payments/", headers=self.super_headers, name="Read: List Payments")
