# Generated by Django 6.0 on 2026-01-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_webhookevent_processed_webhookevent_processed_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="webhookevent",
            name="unique_webhook_event_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_created_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="captured",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authorized", "Authorized"),
                    ("verified", "Verified"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique event ID from Razorpay",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payload",
            field=models.JSONField(help_text="Complete webhook payload"),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="processed",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.RemoveField(
            model_name="webhookevent",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="webhookevent",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="webhookevent",
            name="tenant",
        ),
    ]
