from datetime import timedelta

ACCESS_TOKEN_LIFETIME = timedelta(minutes=60)
REFRESH_TOKEN_LIFETIME = timedelta(days=1)

DEFAULT_PAGE_SIZE = 5
DEFAULT_MAX_PAGE_SIZE = 100
DEFAULT_PAGE_SIZE_QUERY_PARAM = "page_size"

RESET_TOKEN_TTL = 15 * 60
LIFETIME_AMOUNT_PAISE = 499 * 100
RECIPE_CAP = 5
RECIPE_CACHE_TIMEOUT = 15 * 60
INGREDIENT_CACHE_TIMEOUT = 15 * 60

OTP_TIMEOUT = 300
OTP_EXPIRY_MINUTES = 5
OTP_LIMIT_TIMEOUT = 300

USER_RETENTION_DAYS = 90
USER_CLEANUP_DAYS = 7
USER_CLEANUP_TASK_INTERVAL_DAYS = 7
FLUSH_TOKENS_TASK_INTERVAL_DAYS = 1

TASK_MAX_RETRIES = 3
