# Generated by Django 6.0 on 2026-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuisine",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="is_active",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
