# Generated by Django 6.0 on 2026-01-17 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_cuisine_is_active_ingredient_is_active_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="unique_ingredient_per_recipe",
        ),
        migrations.AddField(
            model_name="cuisine",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuisines",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="cuisine",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="cuisine",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_cuisine_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_ingredient_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_recipe_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("tenant", "recipe", "ingredient"),
                name="unique_ingredient_per_recipe_per_tenant",
            ),
        ),
    ]
