# Generated by Django 6.0 on 2026-01-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0003_remove_recipeingredient_unique_ingredient_per_recipe_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuisine",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuisines",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="tenants.tenant",
            ),
        ),
    ]
