# Generated by Django 6.0 on 2026-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_cuisine_tenant_alter_ingredient_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
