# Generated by Django 6.0 on 2026-01-27 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_picture"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipePicture",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("picture", models.ImageField(upload_to="recipes/pictures/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="picture",
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["name"], name="recipe_name_idx"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["sharing_status"], name="recipe_sharing_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["description"], name="recipe_description_idx"),
        ),
        migrations.AddField(
            model_name="recipepicture",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_pictures",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipepicture",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_pictures",
                to="tenants.tenant",
            ),
        ),
    ]
